Repository dhghf/matrix-plugin, pull requests merged in 2020-06, with the labels that each got.

#4 Built for 0.9.4
  README.md
  polo-bukkit/src/main/java/dev/dhdf/polo/bukkit/MCListener.java
  polo-common/src/main/java/dev/dhdf/polo/types/MCMessage.java
  polo-common/src/main/java/dev/dhdf/polo/types/PoloPlayer.java
  polo-common/src/main/java/dev/dhdf/polo/webclient/WebClient.java
  polo-common/src/main/java/dev/dhdf/polo/webclient/types/MxMessage.java
  ship.sh
Labels: bug, documentation, enhancement

#5 Reconnection fixes
  polo-common/src/main/java/dev/dhdf/polo/webclient/WebClient.java
Labels: bug

#6 Fix port check
  polo-bukkit/src/main/java/dev/dhdf/polo/bukkit/Main.java
Labels: bug

#7 Use the scheduler provided by the API for Sync
  polo-bukkit/src/main/java/dev/dhdf/polo/bukkit/Main.java
  polo-common/src/main/java/dev/dhdf/polo/util/Sync.java
Labels: enhancement

#8 Fixes
  polo-bukkit/src/main/java/dev/dhdf/polo/bukkit/Main.java
  polo-bukkit/src/main/resources/config.yml
  polo-common/src/main/java/dev/dhdf/polo/webclient/WebClient.java
Labels: bug, enhancement

#10 Implement Sponge plugin
  build.gradle
  polo-bukkit/build.gradle
  polo-sponge/build.gradle
  polo-sponge/src/main/java/dev/dhdf/polo/sponge/Main.java
  settings.gradle
Labels: enhancement

#11 Fix timer period to 5sec instead of >4mins
  polo-bukkit/src/main/java/dev/dhdf/polo/bukkit/Main.java
Labels: bug
